#!/usr/bin/env node

/**
 * Module dependencies.
 */
var program = require('commander');
var fs = require('fs');
var file = process.argv[2];
var newFile = process.argv[3];
var options = { encoding: 'utf8' };
var path = require('path');
var lib = require('./index');


program
  .version('0.0.1')
  .option('')
  .parse(process.argv);

var newFunction = function() {
	fs.readFile(file, options, function (err, contents) {
	fs.writeFile(newFile, contents, options, function (err) {
	if (err) throw err;
  	console.log('It\'s saved!');
  	});
});
};





// fileShreader(function(err, files) {});

//Splits the default template into two parts on {{ content }}
lib.fileReader(path.join(__dirname, 'source/layouts/default.html'), function(err, contents) {
	if (contents.search("{{ content }}") !== -1) {
		var defaultTemplate = contents.split("{{ content }}");
		console.log(defaultTemplate[0]);
		console.log('contents should go in here');
		console.log(defaultTemplate[1]);
	} else {
		console.log('something went wrong!');
	}
});

//Generates a file from the default template and create a new file with its contents

lib.pathReader('source', function(err, files) {
	console.log(files);
});



lib.pathReader('source/layouts', function(err, files) {
	var filtered = files.filter(lib.isHtml);
	console.log(filtered);
});

lib.pathReader('source/pages', function(err, files) {
	var filtered = files.filter(lib.isHtml);
	console.log(filtered);
});

