#!/usr/bin/env node

/**
 * Module dependencies.
 */
module.exports = {};
var program = require('commander');
var fs = require('fs');
var file = process.argv[2];
var newFile = process.argv[3];
var options = { encoding: 'utf8' };

program
  .version('0.0.1')
  .option('')
  .parse(process.argv);

var newFunction = function() {
	fs.readFile(file, options, function (err, contents) {
	fs.writeFile(newFile, contents, options, function (err) {
	if (err) throw err;
  	console.log('It\'s saved!');
  	});
});
};



module.exports.fileSaver = function () {
	return true;
};

